sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mlizarraga90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mlizarraga90/docker-react npm run test
