language: generic
sudo: required
services:
  -docker
  
before_install:
  - docker build -t mlizarraga1990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mlizarraga1990/docker-react npm run test
